# Generated by Django 4.2.13 on 2024-07-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
